import { execSync } from 'child_process';
import { writeFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));

const count = execSync('git rev-list --count HEAD').toString().trim();
const sha   = execSync('git rev-parse --short HEAD').toString().trim();

const content = `// Auto-generated by scripts/set-version.mjs — do not edit manually
export const APP_VERSION = 'build ${count} · ${sha}';
`;

const out = join(__dirname, '../src/environments/version.ts');
writeFileSync(out, content, 'utf8');
console.log(`Version set: build ${count} · ${sha}`);
